#!/usr/bin/perl 

# use statements                                                       {{{1
use strict;
use warnings;
use 5.006;
use 5.022.0;
use English qw(-no_match_vars);
use Term::Complete;
use experimental 'switch';

# constants                                                            {{{1
my $SELF     = 'dn-util-complete';
my $TRUE     = 1;
my $SHELL_OK = 0;

# variables                                                            {{{1
my ( $name_single, $name_plural, $output_file, @items );

# process arguments                                                    {{{1
# - cycle through @ARGV                                                {{{2
while ( my $opt = shift @ARGV ) {
    for ($opt) {
        when (/^name-single\z/) {
            my $val = shift @ARGV;
            if ( defined $val and $val ne q{} ) { $name_single = $val; }
        }
        when (/^name-plural\z/) {
            my $val = shift @ARGV;
            if ( defined $val and $val ne q{} ) { $name_plural = $val; }
        }
        when (/^output-file\z/) {
            my $val = shift @ARGV;
            if ( defined $val and $val ne q{} ) { $output_file = $val; }
        }
        when (/^fail-if-no-items\z/) {
            my $val = shift @ARGV;
            if ( defined $val and $val ne q{} ) {
                $fail_if_no_items = $val;
            }
        }
        when (/^fail-if-no-selection\z/) {
            my $val = shift @ARGV;
            if ( defined $val and $val ne q{} ) {
                $fail_if_no_selection = $val;
            }
        }
        default { push @items, $opt; }
    }
}

# - check required variables have been set                             {{{2
if ( not $name_single ) {
    die "$SELF: no \"name-single\" argument provided\n";
}
if ( not $name_plural ) {
    die "$SELF: no \"name-plural\" argument provided\n";
}
if ( not $output_file ) {
    die "$SELF: no \"output-file\" argument provided\n";
}
if ( not @items ) { die "$SELF: no $name_plural provided\n"; } 

# select item using completion                                         {{{1
say "Completion shortcuts available while entering $name_single:";
say '  <Tab>    - attempt completion';
say '  <Ctrl-d> - print completion list';
say '  <BKSP>   - erase a character';
say '  <Ctrl-u> - erase current input';
my $item;
$item = Term::Complete::Complete( "Enter $name_single: ", @items );
if ( not $item ) { die "$SELF: no $name_single selected\n"; }

# output result                                                        {{{1
open my $fh, '>', $output_file
    or die "$SELF: unable to open '$output_file' for output";
print {$fh} $item
    or die "$SELF: unable to write to output file '$output_file'";
close $fh;

# exit indicating success                                              {{{1
exit $SHELL_OK;    #                                                   }}}1

# vim:fdm=marker:
